name: Medo-X-LiteManager

on:
  workflow_dispatch:
    inputs:
      referral_link:
        description: 'Enter your referral link'
        required: true

jobs:
  build:
    name: Start Building...
    runs-on: windows-2019
    timeout-minutes: 9999
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/MedoGhnam/SWS/refs/heads/main/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Starting RDP
        run: cmd /c show.bat

      - name: Saving Referral Link
        run: |
          echo ${{ github.event.inputs.referral_link }} > C:\Users\Public\Desktop\sws\config.txt

      - name: Running Start.bat
        run: |
          cd C:\Users\Public\Desktop\sws
          cmd /c Start.bat > nul 2>&1

      - name: Medo Says Enjoy ;)
        run: cmd /c loop.bat
